### ISSUE TITLE
Docker + nginx-systemtap-toolkit

### ISSUE THREAD

**Issue by zot24** [openresty/openresty-systemtap-toolkit#24]
Is there anyone running this tools inside a Docker container? we are running OpenResty into a Docker container I did the installation of everything needed however I can not access to the nginx /proc/{pid}/exe as root so your scripts throw the following error:

```
Nginx process 7290 is not running or you do not have enough permissions.
```

Is there a way to fix this problem and be able to run this tools inside a Docker container? these Docker issues may be related but I'm not 100% sure not an expert on Docker:

https://github.com/docker/docker/issues/6800
https://github.com/docker/docker/issues/11049

Does everything should work fine if I run the script as root isn't it?

**Comment by agentzh** [comment]
@zot24 You (at least) need enough permissions to run the tools. Usually you don't have to be root. Making your current user under the stapusr and stapdev user groups should be sufficient if you already have enough permissions with the target processes being traced. But if you are looking at a process run by privileged users like root, then you have to be root anyway in order to look inside that process for obvious reasons :)

**Comment by agentzh** [comment]
@zot24 Disclaimer: I never use systemtap inside a docker container myself.

**Comment by horan-geeker** [comment]
I'm root user, also have this problem
```shell
root@e411db0402a3:/debug# ./ngx-lua-shdict -p 8 -f --dict shared_dict --key request_limit --luajit20
Nginx process 8 is not running or you do not have enough permissions.
```

**Comment by agentzh** [comment]
This project is already superseded by [OpenResty XRay](https://openresty.com/en/xray/) and the latter does not have problems analyzing docker/k8s containers.
